theme = "hugo-theme-learn"
relativeurls = true
languageCode = "en-us"
title = "Learn Galaxy and Tripal Galaxy"
themesdir = "themes"
publishdir = "../statonlab.github.io/learn-galaxy-and-tripal-galaxy/"

[params]
  themeVariant = "blue"
  menu = ["Galaxy"]

[outputs]
  home = [ "HTML", "RSS", "JSON"]




