theme = "hugo-theme-learn"
relativeurls = true
languageCode = "en-us"
title = "Learn Galaxy and Tripal Galaxy"
themesdir = "themes"
publishDir = "docs"


[params]
  themeVariant = "blue"
  menu = ["Galaxy"]

[outputs]
  home = [ "HTML", "RSS", "JSON"]




